export const RoleModule: any[] = [
    // { name: 'Dashboard', moduleId: 1,readOperation:true,writeOperation:false,checked:false },
    { name: 'Unit', moduleId: 2, readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Department', moduleId: 3, readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Section', moduleId: 4, readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Group', moduleId: 5, readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Employment Type', moduleId: 6, readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Employee', moduleId: 7, readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Company Objectives', moduleId: 8, readOperation: true, writeOperation: false, checked: true, disabled: true },
    { name: 'Department Objectives', moduleId: 9, readOperation: true, writeOperation: false, checked: true, disabled: true },
    { name: 'Employee Objectives', moduleId: 10, readOperation: true, writeOperation: true, checked: true, disabled: true },
    { name: 'Roles', moduleId: 11, readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Assign Appraisal Roles', moduleId: 12, readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Appraisal Plan', moduleId: 13, readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'My Appraisees', moduleId: 14, readOperation: true, writeOperation: true, checked: false, disabled: false },
    { name: 'Competency Parameter', moduleId: 15, readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Promotion Eligibility', moduleId: 16, readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Company Parameter', moduleId:20 , readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Rating Configuration', moduleId:21 , readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Grade Configuration', moduleId:22 , readOperation: true, writeOperation: false, checked: false, disabled: false },
    { name: 'Report', moduleId:23 , readOperation: true, writeOperation: false, checked: false, disabled: false },
];